- name: Wipe web app
  include_tasks: 0-wipe.yml
  tags: [web_app, web_app_wipe]
  when: web_app_full_wipe

- name: Deploy web app
  block:
  - name: Create web app dir
    file:
      path: "{{ web_app_base_dir }}"
      state: directory
      mode: '0755'

  - name: Template the docker-compose.yml
    template:
      src: docker-compose.yml.j2
      dest: "{{ web_app_base_dir }}/docker-compose.yml"
      owner: root
      group: root
      mode: "0600"

  - name: Run docker-compose services
    docker_compose:
      project_src: "{{ web_app_base_dir }}"
      state: present
      pull: true
  tags: ["web_app"]
